### pedido de fotos                                
GET https://foto-api.vercel.app/api/fotos

### crear foto
POST  https://foto-api.vercel.app/api/fotos
Content-Type: application/json

{
    "foto" : "https://ibb.c"
}

### borrar todas las fotos
DELETE https://foto-api.vercel.app/api/fotos/deleteAll
